version: 2
jobs:
  build-and-test:
    docker:
      - image: 813968012009.dkr.ecr.us-east-1.amazonaws.com/circleci-openjdk8-8u162
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    # The below is required because of https://discuss.circleci.com/t/circle-working-directory-doesnt-expand/17007
    working_directory: /home/circleci/project
    steps:
      - checkout
      - restore_cache:
          # if you ever need to invalidate the cache, simply bump the version number
          keys:
            - v1-maven-{{ .Branch }}-{{ checksum "pom.xml" }}
            - v1-maven-{{ .Branch }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-maven-{{ .Branch }}-{{ checksum "pom.xml" }}
      - setup_remote_docker
      - run:
          name: Build, run, and test
          command: /electrum/bin/postmanTestJava.sh billpaytest_server_tests
      - run:
          name: Save docker image for caching
          command: |
            mkdir -p docker-cache
            docker save -o docker-cache/test-server-image.tar $CIRCLE_PROJECT_REPONAME
      - persist_to_workspace:
          root: docker-cache
          paths:
            - test-server-image.tar
  deploy:
    docker:
      - image: circleci/openjdk:8u162-jdk-stretch
    environment:
      HEROKU_APP: billpay-test-server
      DOCKER_REPONAME: electrum/billpay-test-server
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git master
      - attach_workspace:
          at: docker-cache
      - run:
          name: Export service interface version
          # tag with major version of underlying service interface
          command: |
            echo "export TAG=$(mvn -q -Dexec.executable=echo -Dexec.args='${billpay-version}' --non-recursive exec:exec | cut -c1)" >> $BASH_ENV
      - setup_remote_docker
      - run:
          name: Deploy image to Docker Hub
          command: |
            docker load < docker-cache/test-server-image.tar
            docker tag $CIRCLE_PROJECT_REPONAME $DOCKER_REPONAME:$TAG
            echo $DOCKERHUB_PWD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKER_REPONAME:$TAG
  build-with-latest-deps:
    docker:
      - image: 813968012009.dkr.ecr.us-east-1.amazonaws.com/circleci-openjdk8-8u162
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - restore_cache:
          # if you ever need to invalidate the cache, simply bump the version number
          keys:
            - v1-maven-{{ .Branch }}-{{ checksum "pom.xml" }}
            - v1-maven-{{ .Branch }}
      - run:
          name: Update pom with latest Electrum deps
          command: /electrum/bin/updatePomWithLatestDeps.sh
      - setup_remote_docker
      - run:
          name: Test, but only if any Electrum dependencies changed
          command: /electrum/bin/postmanTestWithUpdatedDepsJava.sh billpaytest_server_tests
      - run:
          name: Notify success to slack
          command: /electrum/bin/notifySlackDepBuildSucceeded.sh
          when: on_success
      - run:
          name: Notify failure to slack
          command: /electrum/bin/notifySlackDepBuildFailed.sh
          when: on_fail

workflows:
  version: 2
  commit:
    jobs:
      - build-and-test:
          context: java
      - deploy:
          context: java
          requires:
            - build-and-test
          filters:
            branches:
              only: master
  nightly:
    jobs:
      - build-with-latest-deps:
          context: java
    triggers:
      - schedule:
          # every night at 00:00 SAST (22:00 UTC)
          cron: "00 22 * * *"
          filters:
            branches:
              only:
                - master
